name: Deploy Mkdocs to GitHub Pages
on:
  push:
    branches: 
      - main
      - generate-index
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    
    - name: Set up Python 3
      uses: actions/setup-python@main
      with:
        python-version: '3.x'

    - name: Install Poetry
      uses: snok/install-poetry@v1.3

    - name: Install Dependencies.
      run: poetry install
    
    - name: Build Documentation.
      run: make build-docs

    - name: Deploy
      run: poetry run mkdocs gh-deploy
